import FiberManualRecordIcon from '@material-ui/icons/FiberManualRecord';

export const Questions = [
  { value: 'Yes', label: 'Yes' },
  { value: 'No', label: 'No' },
];

export const AlbertaCities = [
  { value: 'Airdrie', label: 'Airdrie' },
  { value: 'Alder Flats', label: 'Alder Flats' },
  { value: 'Altario', label: 'Altario' },
  { value: 'Amisk', label: 'Amisk' },
  { value: 'Antler Lake', label: 'Antler Lake' },
  { value: 'Arrowwood', label: 'Arrowwood' },
  { value: 'Athabasca', label: 'Athabasca' },
  { value: 'Atikameg', label: 'Atikameg' },
  { value: 'Atmore', label: 'Atmore' },
  { value: 'Banff', label: 'Banff' },
  { value: 'Barnwell', label: 'Barnwell' },
  { value: 'Barrhead', label: 'Barrhead' },
  { value: 'Bashaw', label: 'Bashaw' },
  { value: 'Bassano', label: 'Bassano' },
  { value: 'Bear Canyon', label: 'Bear Canyon' },
  { value: 'Beaumont', label: 'Beaumont' },
  { value: 'Beauvallon', label: 'Beauvallon' },
  { value: 'Beaver Lake', label: 'Beaver Lake' },
  { value: 'Beaver Mines', label: 'Beaver Mines' },
  { value: 'Beaverlodge', label: 'Beaverlodge' },
  { value: 'Beazer', label: 'Beazer' },
  { value: 'Beiseker', label: 'Beiseker' },
  { value: 'Bellevue', label: 'Bellevue' },
  { value: 'Bellis', label: 'Bellis' },
  { value: 'Benchlands', label: 'Benchlands' },
  { value: 'Bentley', label: 'Bentley' },
  { value: 'Berwyn', label: 'Berwyn' },
  { value: 'Bezanson', label: 'Bezanson' },
  { value: 'Big Valley', label: 'Big Valley' },
  { value: 'Bindloss', label: 'Bindloss' },
  { value: 'Birch Cove', label: 'Birch Cove' },
  { value: 'Bircham', label: 'Bircham' },
  { value: 'Birchcliff', label: 'Birchcliff' },
  { value: 'Bittern Lake', label: 'Bittern Lake' },
  { value: 'Black Diamond', label: 'Black Diamond' },
  { value: 'Blackfoot', label: 'Blackfoot' },
  { value: 'Blackie', label: 'Blackie' },
  { value: 'Blue Ridge', label: 'Blue Ridge' },
  { value: 'Bluesky', label: 'Bluesky' },
  { value: 'Bluffton', label: 'Bluffton' },
  { value: 'Bodo', label: 'Bodo' },
  { value: 'Bon Accord', label: 'Bon Accord' },
  { value: 'Bondiss', label: 'Bondiss' },
  { value: 'Bonnyville', label: 'Bonnyville' },
  { value: 'Bonnyville Beach', label: 'Bonnyville Beach' },
  { value: 'Botha', label: 'Botha' },
  { value: 'Bottrel', label: 'Bottrel' },
  { value: 'Bow Island', label: 'Bow Island' },
  { value: 'Bowden', label: 'Bowden' },
  { value: 'Boyle', label: 'Boyle' },
  { value: 'Bragg Creek', label: 'Bragg Creek' },
  { value: 'Brant', label: 'Brant' },
  { value: 'Breton', label: 'Breton' },
  { value: 'Breynat', label: 'Breynat' },
  { value: 'Brooks', label: 'Brooks' },
  { value: 'Brosseau', label: 'Brosseau' },
  { value: 'Brownfield', label: 'Brownfield' },
  { value: 'Brownvale', label: 'Brownvale' },
  { value: 'Bruce', label: 'Bruce' },
  { value: 'Bruderheim', label: 'Bruderheim' },
  { value: 'Brule', label: 'Brule' },
  { value: 'Buck Creek', label: 'Buck Creek' },
  { value: 'Buck Lake', label: 'Buck Lake' },
  { value: 'Buffalo Lake Settlement', label: 'Buffalo Lake Settlement' },
  { value: 'Buford', label: 'Buford' },
  { value: 'Burdett', label: 'Burdett' },
  { value: 'Burnstick Lake', label: 'Burnstick Lake' },
  { value: 'Busby', label: 'Busby' },
  { value: 'Byemoor', label: 'Byemoor' },
  { value: 'Cadogan', label: 'Cadogan' },
  { value: 'Cadomin', label: 'Cadomin' },
  { value: 'Cadotte Lake', label: 'Cadotte Lake' },
  { value: 'Calahoo', label: 'Calahoo' },
  { value: 'Calgary', label: 'Calgary' },
  { value: 'Calling Lake', label: 'Calling Lake' },
  { value: 'Calmar', label: 'Calmar' },
  { value: 'Campsie', label: 'Campsie' },
  { value: 'Camrose', label: 'Camrose' },
  { value: 'Canmore', label: 'Canmore' },
  { value: 'Canyon Creek', label: 'Canyon Creek' },
  { value: 'Carbon', label: 'Carbon' },
  { value: 'Carbondale', label: 'Carbondale' },
  { value: 'Cardiff', label: 'Cardiff' },
  { value: 'Cardston', label: 'Cardston' },
  { value: 'Carmangay', label: 'Carmangay' },
  { value: 'Caroline', label: 'Caroline' },
  { value: 'Carseland', label: 'Carseland' },
  { value: 'Carstairs', label: 'Carstairs' },
  { value: 'Carvel', label: 'Carvel' },
  { value: 'Carway', label: 'Carway' },
  { value: 'Caslan', label: 'Caslan' },
  { value: 'Castle Island', label: 'Castle Island' },
  { value: 'Castor', label: 'Castor' },
  { value: 'Cayley', label: 'Cayley' },
  { value: 'Cereal', label: 'Cereal' },
  { value: 'Cessford', label: 'Cessford' },
  { value: 'Champion', label: 'Champion' },
  { value: 'Chancellor', label: 'Chancellor' },
  { value: 'Chard', label: 'Chard' },
  { value: 'Chauvin', label: 'Chauvin' },
  { value: 'Cheadle', label: 'Cheadle' },
  { value: 'Cherhill', label: 'Cherhill' },
  { value: 'Cherry Grove', label: 'Cherry Grove' },
  { value: 'Chestermere', label: 'Chestermere' },
  { value: 'Child Lake 164A', label: 'Child Lake 164A' },
  { value: 'Chin', label: 'Chin' },
  { value: 'Chinook', label: 'Chinook' },
  { value: 'Chipman', label: 'Chipman' },
  { value: 'Chisholm', label: 'Chisholm' },
  { value: 'Clairmont', label: 'Clairmont' },
  { value: 'Clandonald', label: 'Clandonald' },
  { value: 'Claresholm', label: 'Claresholm' },
  { value: 'Cleardale', label: 'Cleardale' },
  { value: 'Clive', label: 'Clive' },
  { value: 'Cluny', label: 'Cluny' },
  { value: 'Clyde', label: 'Clyde' },
  { value: 'Coaldale', label: 'Coaldale' },
  { value: 'Coalhurst', label: 'Coalhurst' },
  { value: 'Cochrane', label: 'Cochrane' },
  { value: 'Cochrane Lake', label: 'Cochrane Lake' },
  { value: 'Cold Lake', label: 'Cold Lake' },
  { value: 'Colinton', label: 'Colinton' },
  { value: 'Collingwood Cove', label: 'Collingwood Cove' },
  { value: 'Compeer', label: 'Compeer' },
  { value: 'Condor', label: 'Condor' },
  { value: 'Conklin', label: 'Conklin' },
  { value: 'Conrich', label: 'Conrich' },
  { value: 'Consort', label: 'Consort' },
  { value: 'Coronation', label: 'Coronation' },
  { value: 'Coutts', label: 'Coutts' },
  { value: 'Cowley', label: 'Cowley' },
  { value: 'Craigmyle', label: 'Craigmyle' },
  { value: 'Cremona', label: 'Cremona' },
  { value: 'Crossfield', label: 'Crossfield' },
  { value: 'Crowsnest Pass', label: 'Crowsnest Pass' },
  { value: 'Crystal Springs', label: 'Crystal Springs' },
  { value: 'Cynthia', label: 'Cynthia' },
  { value: 'Czar', label: 'Czar' },
  { value: 'Dalemead', label: 'Dalemead' },
  { value: 'Dalroy', label: 'Dalroy' },
  { value: 'Dapp', label: 'Dapp' },
  { value: 'Daysland', label: 'Daysland' },
  { value: 'De Winton', label: 'De Winton' },
  { value: "Dead Man'S Flats", label: "Dead Man'S Flats" },
  { value: 'Deadwood', label: 'Deadwood' },
  { value: 'Debolt', label: 'Debolt' },
  { value: 'Del Bonita', label: 'Del Bonita' },
  { value: 'Delacour', label: 'Delacour' },
  { value: 'Delburne', label: 'Delburne' },
  { value: 'Delia', label: 'Delia' },
  { value: 'Demmitt', label: 'Demmitt' },
  { value: 'Derwent', label: 'Derwent' },
  { value: 'Desert Blume', label: 'Desert Blume' },
  { value: 'Desmarais', label: 'Desmarais' },
  { value: 'Devon', label: 'Devon' },
  { value: 'Dewberry', label: 'Dewberry' },
  { value: 'Diamond City', label: 'Diamond City' },
  { value: 'Dickson', label: 'Dickson' },
  { value: 'Didsbury', label: 'Didsbury' },
  { value: 'Dimsdale', label: 'Dimsdale' },
  { value: 'Dixonville', label: 'Dixonville' },
  { value: 'Donalda', label: 'Donalda' },
  { value: 'Donatville', label: 'Donatville' },
  { value: 'Donnelly', label: 'Donnelly' },
  { value: 'Dorothy', label: 'Dorothy' },
  { value: 'Drayton Valley', label: 'Drayton Valley' },
  { value: 'Driftpile', label: 'Driftpile' },
  { value: 'Drumheller', label: 'Drumheller' },
  { value: 'Duchess', label: 'Duchess' },
  { value: 'Duffield', label: 'Duffield' },
  { value: 'Duhamel', label: 'Duhamel' },
  { value: 'Dunmore', label: 'Dunmore' },
  { value: 'Duvernay', label: 'Duvernay' },
  { value: 'Eaglesham', label: 'Eaglesham' },
  { value: 'Eckville', label: 'Eckville' },
  { value: 'Edberg', label: 'Edberg' },
  { value: 'Edgerton', label: 'Edgerton' },
  { value: 'Edmonton', label: 'Edmonton' },
  { value: 'Edson', label: 'Edson' },
  { value: 'Edwand', label: 'Edwand' },
  { value: 'Egremont', label: 'Egremont' },
  { value: 'Elizabeth Metis Settlement', label: 'Elizabeth Metis Settlement' },
  { value: 'Elk Point', label: 'Elk Point' },
  { value: 'Ellscott', label: 'Ellscott' },
  { value: 'Elmworth', label: 'Elmworth' },
  { value: 'Elnora', label: 'Elnora' },
  { value: 'Empress', label: 'Empress' },
  { value: 'Enchant', label: 'Enchant' },
  { value: 'Endiang', label: 'Endiang' },
  { value: 'Enilda', label: 'Enilda' },
  { value: 'Ensign', label: 'Ensign' },
  { value: 'Entwistle', label: 'Entwistle' },
  { value: 'Erskine', label: 'Erskine' },
  { value: 'Etzikom', label: 'Etzikom' },
  { value: 'Evansburg', label: 'Evansburg' },
  { value: 'Exshaw', label: 'Exshaw' },
  { value: 'Fabyan', label: 'Fabyan' },
  { value: 'Fairview', label: 'Fairview' },
  { value: 'Falher', label: 'Falher' },
  { value: 'Fallis', label: 'Fallis' },
  { value: 'Falun', label: 'Falun' },
  { value: 'Faust', label: 'Faust' },
  { value: 'Fawcett', label: 'Fawcett' },
  { value: 'Ferintosh', label: 'Ferintosh' },
  { value: 'Fishing Lake Metis Settlement', label: 'Fishing Lake Metis Settlement' },
  { value: 'Flatbush', label: 'Flatbush' },
  { value: 'Fleet', label: 'Fleet' },
  { value: 'Foremost', label: 'Foremost' },
  { value: 'Forestburg', label: 'Forestburg' },
  { value: 'Fort Assiniboine', label: 'Fort Assiniboine' },
  { value: 'Fort Chipewyan', label: 'Fort Chipewyan' },
  { value: 'Fort Kent', label: 'Fort Kent' },
  { value: 'Fort Macleod', label: 'Fort Macleod' },
  { value: 'Fort McKay', label: 'Fort McKay' },
  { value: 'Fort McMurray', label: 'Fort McMurray' },
  { value: 'Fort Saskatchewan', label: 'Fort Saskatchewan' },
  { value: 'Fort Vermilion', label: 'Fort Vermilion' },
  { value: 'Fox Creek', label: 'Fox Creek' },
  { value: 'Frog Lake', label: 'Frog Lake' },
  { value: 'Gadsby', label: 'Gadsby' },
  { value: 'Gainford', label: 'Gainford' },
  { value: 'Galahad', label: 'Galahad' },
  { value: 'Gem', label: 'Gem' },
  { value: 'Ghost Lake', label: 'Ghost Lake' },
  { value: 'Gibbons', label: 'Gibbons' },
  { value: 'Gift Lake', label: 'Gift Lake' },
  { value: 'Girouxville', label: 'Girouxville' },
  { value: 'Gleichen', label: 'Gleichen' },
  { value: 'Glendon', label: 'Glendon' },
  { value: 'Glenevis', label: 'Glenevis' },
  { value: 'Glenwood', label: 'Glenwood' },
  { value: 'Golden Days', label: 'Golden Days' },
  { value: 'Goose Lake', label: 'Goose Lake' },
  { value: 'Grande Prairie', label: 'Grande Prairie' },
  { value: 'Grandeview', label: 'Grandeview' },
  { value: 'Grassy Lake', label: 'Grassy Lake' },
  { value: 'Greenshields', label: 'Greenshields' },
  { value: 'Grimshaw', label: 'Grimshaw' },
  { value: 'Grouard', label: 'Grouard' },
  { value: 'Gull Lake', label: 'Gull Lake' },
  { value: 'Guy', label: 'Guy' },
  { value: 'Hairy Hill', label: 'Hairy Hill' },
  { value: 'Half Moon Bay', label: 'Half Moon Bay' },
  { value: 'Half Moon Lake', label: 'Half Moon Lake' },
  { value: 'Halkirk', label: 'Halkirk' },
  { value: 'Hanna', label: 'Hanna' },
  { value: 'Hardisty', label: 'Hardisty' },
  { value: 'Harvie Heights', label: 'Harvie Heights' },
  { value: 'Hastings Lake', label: 'Hastings Lake' },
  { value: 'Heritage Pointe', label: 'Heritage Pointe' },
  { value: 'Herronton', label: 'Herronton' },
  { value: 'Iddesleigh', label: 'Iddesleigh' },
  { value: 'Innisfree', label: 'Innisfree' },
  { value: 'Irricana', label: 'Irricana' },
  { value: 'Irvine', label: 'Irvine' },
  { value: 'Josephburg', label: 'Josephburg' },
  { value: 'Kathyrn', label: 'Kathyrn' },
  { value: 'Keephills', label: 'Keephills' },
  { value: 'Keg River', label: 'Keg River' },
  { value: 'Kimball', label: 'Kimball' },
  { value: 'Kirriemuir', label: 'Kirriemuir' },
  { value: 'Kitscoty', label: 'Kitscoty' },
  { value: 'La Corey', label: 'La Corey' },
  { value: 'La Crete', label: 'La Crete' },
  { value: 'La Glace', label: 'La Glace' },
  { value: 'Lac Des Arcs', label: 'Lac Des Arcs' },
  { value: 'Lac La Biche', label: 'Lac La Biche' },
  { value: 'Lafond', label: 'Lafond' },
  { value: 'Lake Louise', label: 'Lake Louise' },
  { value: 'Lake Newell Resort', label: 'Lake Newell Resort' },
  { value: 'Lakeview', label: 'Lakeview' },
  { value: 'Lamont', label: 'Lamont' },
  { value: 'Lamoureux', label: 'Lamoureux' },
  { value: 'Lancaster Park', label: 'Lancaster Park' },
  { value: 'Landry Heights', label: 'Landry Heights' },
  { value: 'Langdon', label: 'Langdon' },
  { value: 'Larkspur', label: 'Larkspur' },
  { value: 'Lavoy', label: 'Lavoy' },
  { value: 'Leavitt', label: 'Leavitt' },
  { value: 'Leduc', label: 'Leduc' },
  { value: 'Leedale', label: 'Leedale' },
  { value: 'Legal', label: 'Legal' },
  { value: 'Leslieville', label: 'Leslieville' },
  { value: 'Lethbridge', label: 'Lethbridge' },
  { value: 'Lindbergh', label: 'Lindbergh' },
  { value: 'Linden', label: 'Linden' },
  { value: 'Linn Valley', label: 'Linn Valley' },
  { value: 'Little Buffalo', label: 'Little Buffalo' },
  { value: 'Little Smoky', label: 'Little Smoky' },
  { value: 'Lloydminster', label: 'Lloydminster' },
  { value: 'Lodgepole', label: 'Lodgepole' },
  { value: 'Lomond', label: 'Lomond' },
  { value: 'Long Lake', label: 'Long Lake' },
  { value: 'Longview', label: 'Longview' },
  { value: 'Looma', label: 'Looma' },
  { value: 'Lottie Lake', label: 'Lottie Lake' },
  { value: 'Lougheed', label: 'Lougheed' },
  { value: 'Lousana', label: 'Lousana' },
  { value: 'Lowland Heights', label: 'Lowland Heights' },
  { value: 'Lundbreck', label: 'Lundbreck' },
  { value: 'Lyalta', label: 'Lyalta' },
  { value: 'Ma-Me-O Beach', label: 'Ma-Me-O Beach' },
  { value: 'Mackay', label: 'Mackay' },
  { value: 'Madden', label: 'Madden' },
  { value: 'Magrath', label: 'Magrath' },
  { value: 'Mallaig', label: 'Mallaig' },
  { value: 'Manning', label: 'Manning' },
  { value: 'Mannville', label: 'Mannville' },
  { value: 'Manola', label: 'Manola' },
  { value: 'Manyberries', label: 'Manyberries' },
  { value: 'Marie Reine', label: 'Marie Reine' },
  { value: 'Marlboro', label: 'Marlboro' },
  { value: 'Marten Beach', label: 'Marten Beach' },
  { value: 'Marwayne', label: 'Marwayne' },
  { value: 'Mayerthorpe', label: 'Mayerthorpe' },
  { value: 'McLaughlin', label: 'McLaughlin' },
  { value: 'McLennan', label: 'McLennan' },
  { value: 'Meanook', label: 'Meanook' },
  { value: 'Mearns', label: 'Mearns' },
  { value: 'Medicine Hat', label: 'Medicine Hat' },
  { value: 'Meeting Creek', label: 'Meeting Creek' },
  { value: 'Metiskow', label: 'Metiskow' },
  { value: 'Mewatha Beach', label: 'Mewatha Beach' },
  { value: 'Michichi', label: 'Michichi' },
  { value: 'Milk River', label: 'Milk River' },
  { value: 'Millarville', label: 'Millarville' },
  { value: 'Millet', label: 'Millet' },
  { value: 'Milo', label: 'Milo' },
  { value: 'Minburn', label: 'Minburn' },
  { value: 'Mirror', label: 'Mirror' },
  { value: 'Monarch', label: 'Monarch' },
  { value: 'Monitor', label: 'Monitor' },
  { value: 'Moon River Estates', label: 'Moon River Estates' },
  { value: 'Morinville', label: 'Morinville' },
  { value: 'Morley', label: 'Morley' },
  { value: 'Morningside', label: 'Morningside' },
  { value: 'Morrin', label: 'Morrin' },
  { value: 'Mossleigh', label: 'Mossleigh' },
  { value: 'Mountain View', label: 'Mountain View' },
  { value: 'Mulhurst Bay', label: 'Mulhurst Bay' },
  { value: 'Mundare', label: 'Mundare' },
  { value: 'Munson', label: 'Munson' },
  { value: 'Musidora', label: 'Musidora' },
  { value: 'Myrnam', label: 'Myrnam' },
  { value: 'Nakamun Park', label: 'Nakamun Park' },
  { value: 'Namaka', label: 'Namaka' },
  { value: 'Namao', label: 'Namao' },
  { value: 'Nampa', label: 'Nampa' },
  { value: 'Nanton', label: 'Nanton' },
  { value: 'Neerlandia', label: 'Neerlandia' },
  { value: 'Nestow', label: 'Nestow' },
  { value: 'New Brigden', label: 'New Brigden' },
  { value: 'New Dayton', label: 'New Dayton' },
  { value: 'New Norway', label: 'New Norway' },
  { value: 'New Sarepta', label: 'New Sarepta' },
  { value: 'Newbrook', label: 'Newbrook' },
  { value: 'Nightingale', label: 'Nightingale' },
  { value: 'Nisku', label: 'Nisku' },
  { value: 'Niton Junction', label: 'Niton Junction' },
  { value: 'Nobleford', label: 'Nobleford' },
  { value: 'Nordegg', label: 'Nordegg' },
  { value: 'Norglenwold', label: 'Norglenwold' },
  { value: 'Norris Beach', label: 'Norris Beach' },
  { value: 'North Cooking Lake', label: 'North Cooking Lake' },
  { value: 'North Star', label: 'North Star' },
  { value: 'Notikewin', label: 'Notikewin' },
  { value: 'Okotoks', label: 'Okotoks' },
  { value: 'Opal', label: 'Opal' },
  { value: 'Orton', label: 'Orton' },
  { value: 'Paddle Prairie', label: 'Paddle Prairie' },
  { value: 'Paradise Valley', label: 'Paradise Valley' },
  { value: 'Patricia', label: 'Patricia' },
  { value: 'Peerless Lake', label: 'Peerless Lake' },
  { value: 'Pelican Point', label: 'Pelican Point' },
  { value: 'Peoria', label: 'Peoria' },
  { value: 'Picture Butte', label: 'Picture Butte' },
  { value: 'Pincher Station', label: 'Pincher Station' },
  { value: 'Pine Sands', label: 'Pine Sands' },
  { value: 'Plamondon', label: 'Plamondon' },
  { value: 'Poplar Bay', label: 'Poplar Bay' },
  { value: 'Poplar Ridge', label: 'Poplar Ridge' },
  { value: 'Priddis', label: 'Priddis' },
  { value: 'Priddis Greens', label: 'Priddis Greens' },
  { value: 'Purple Springs', label: 'Purple Springs' },
  { value: 'Rainbow Lake', label: 'Rainbow Lake' },
  { value: 'Raymond', label: 'Raymond' },
  { value: 'Red Deer', label: 'Red Deer' },
  { value: 'Redcliff', label: 'Redcliff' },
  { value: 'Redwater', label: 'Redwater' },
  { value: 'Richdale', label: 'Richdale' },
  { value: 'Rimbey', label: 'Rimbey' },
  { value: 'Rivercourse', label: 'Rivercourse' },
  { value: 'Riviere Qui Barre', label: 'Riviere Qui Barre' },
  { value: 'Rochfort Bridge', label: 'Rochfort Bridge' },
  { value: 'Rolling Hills', label: 'Rolling Hills' },
  { value: 'Rosebud', label: 'Rosebud' },
  { value: 'Round Hill', label: 'Round Hill' },
  { value: 'Rowley', label: 'Rowley' },
  { value: 'Rycroft', label: 'Rycroft' },
  { value: 'Ryley', label: 'Ryley' },
  { value: 'Sandy Lake', label: 'Sandy Lake' },
  { value: 'Scandia', label: 'Scandia' },
  { value: 'Schuler', label: 'Schuler' },
  { value: 'Seba Beach', label: 'Seba Beach' },
  { value: 'Sedalia', label: 'Sedalia' },
  { value: 'Sexsmith', label: 'Sexsmith' },
  { value: 'Shepard', label: 'Shepard' },
  { value: 'Sherwood Park', label: 'Sherwood Park' },
  { value: 'Sibbald', label: 'Sibbald' },
  { value: 'Siksika', label: 'Siksika' },
  { value: 'Silver Valley', label: 'Silver Valley' },
  { value: 'Skiff', label: 'Skiff' },
  { value: 'Smith', label: 'Smith' },
  { value: 'South Cooking Lake', label: 'South Cooking Lake' },
  { value: 'Spedden', label: 'Spedden' },
  { value: 'Spring Lake', label: 'Spring Lake' },
  { value: 'Springbrook', label: 'Springbrook' },
  { value: 'Spruce Grove', label: 'Spruce Grove' },
  { value: 'St Isidore', label: 'St Isidore' },
  { value: 'St Michael', label: 'St Michael' },
  { value: 'St. Albert', label: 'St. Albert' },
  { value: 'Stand Off', label: 'Stand Off' },
  { value: 'Stavely', label: 'Stavely' },
  { value: 'Sunnynook', label: 'Sunnynook' },
  { value: 'Sunnyslope', label: 'Sunnyslope' },
  { value: 'Telfordville', label: 'Telfordville' },
  { value: 'Tilley', label: 'Tilley' },
  { value: 'Tofield', label: 'Tofield' },
  { value: 'Two Hills', label: 'Two Hills' },
  { value: 'Vegreville', label: 'Vegreville' },
  { value: 'Veteran', label: 'Veteran' },
  { value: 'Village At Pigeon Lake', label: 'Village At Pigeon Lake' },
  { value: 'Villeneuve', label: 'Villeneuve' },
  { value: 'Vulcan', label: 'Vulcan' },
  { value: 'Warner', label: 'Warner' },
  { value: 'Welling', label: 'Welling' },
  { value: 'Welling Station', label: 'Welling Station' },
  { value: 'West Cove', label: 'West Cove' },
  { value: 'Wetaskiwin', label: 'Wetaskiwin' },
  { value: 'White Sands', label: 'White Sands' },
  { value: 'Widewater', label: 'Widewater' },
  { value: 'Wimborne', label: 'Wimborne' },
  { value: 'Withrow', label: 'Withrow' },
  { value: 'Woking', label: 'Woking' },
  { value: 'Woodhouse', label: 'Woodhouse' },
  { value: 'Worsley', label: 'Worsley' },
  { value: 'Wostok', label: 'Wostok' },
  { value: 'Yellowstone', label: 'Yellowstone' },
  { value: 'Youngstown', label: 'Youngstown' }
];

export const Provinces = [
  { value: 'Alberta', label: 'Alberta' },
  { value: 'British Columbia', label: 'British Columbia' },
  { value: 'Manitoba', label: 'Manitoba' },
  { value: 'New Brunswick', label: 'New Brunswick' },
  { value: 'Newfoundland and Labrador', label: 'Newfoundland and Labrador' },
  { value: 'Northwest Territories', label: 'Northwest Territories' },
  { value: 'Nova Scotia', label: 'Nova Scotia' },
  { value: 'Nunavut', label: 'Nunavut' },
  { value: 'Ontario', label: 'Ontario' },
  { value: 'Prince Edward Island', label: 'Prince Edward Island' },
  { value: 'Québec', label: 'Québec' },
  { value: 'Saskatchewan', label: 'Saskatchewan' },
  { value: 'Yukon', label: 'Yukon' },
  { value: 'Other (please specify)', label: 'Other (please specify)'}
];

export const Countries = [
  { value: 'Canada', label: 'Canada' },
  { value: 'United States of America (the)', label: 'United States of America (the)' },
  { value: 'Afghanistan', label: 'Afghanistan' },
  { value: 'Albania', label: 'Albania' },
  { value: 'Algeria', label: 'Algeria' },
  { value: 'American Samoa', label: 'American Samoa' },
  { value: 'Andorra', label: 'Andorra' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Anguilla', label: 'Anguilla' },
  { value: 'Antarctica', label: 'Antarctica' },
  { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Armenia', label: 'Armenia' },
  { value: 'Aruba', label: 'Aruba' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaijan', label: 'Azerbaijan' },
  { value: 'Bahamas (the)', label: 'Bahamas (the)' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Belarus', label: 'Belarus' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Belize', label: 'Belize' },
  { value: 'Benin', label: 'Benin' },
  { value: 'Bermuda', label: 'Bermuda' },
  { value: 'Bhutan', label: 'Bhutan' },
  { value: 'Bolivia (Plurinational State of)', label: 'Bolivia (Plurinational State of)' },
  { value: 'Bonaire, Sint Eustatius and Saba', label: 'Bonaire, Sint Eustatius and Saba' },
  { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Bouvet Island', label: 'Bouvet Island' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'British Indian Ocean Territory (the)', label: 'British Indian Ocean Territory (the)' },
  { value: 'Brunei Darussalam', label: 'Brunei Darussalam' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Burkina Faso', label: 'Burkina Faso' },
  { value: 'Burundi', label: 'Burundi' },
  { value: 'Cabo Verde', label: 'Cabo Verde' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Cameroon', label: 'Cameroon' },
  { value: 'Cayman Islands (the)', label: 'Cayman Islands (the)' },
  { value: 'Central African Republic (the)', label: 'Central African Republic (the)' },
  { value: 'Chad', label: 'Chad' },
  { value: 'Chile', label: 'Chile' },
  { value: 'China', label: 'China' },
  { value: 'Christmas Island', label: 'Christmas Island' },
  { value: 'Cocos (Keeling) Islands (the)', label: 'Cocos (Keeling) Islands (the)' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Comoros (the)', label: 'Comoros (the)' },
  { value: 'Congo (the Democratic Republic of the)', label: 'Congo (the Democratic Republic of the)' },
  { value: 'Congo (the)', label: 'Congo (the)' },
  { value: 'Cook Islands (the)', label: 'Cook Islands (the)' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Curaçao', label: 'Curaçao' },
  { value: 'Cyprus', label: 'Cyprus' },
  { value: 'Czechia', label: 'Czechia' },
  { value: "Côte d'Ivoire", label: "Côte d'Ivoire" },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Djibouti', label: 'Djibouti' },
  { value: 'Dominica', label: 'Dominica' },
  { value: 'Dominican Republic (the)', label: 'Dominican Republic (the)' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
  { value: 'Eritrea', label: 'Eritrea' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Eswatini', label: 'Eswatini' },
  { value: 'Ethiopia', label: 'Ethiopia' },
  { value: 'Falkland Islands (the) [Malvinas]', label: 'Falkland Islands (the) [Malvinas]' },
  { value: 'Faroe Islands (the)', label: 'Faroe Islands (the)' },
  { value: 'Fiji', label: 'Fiji' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'French Guiana', label: 'French Guiana' },
  { value: 'French Polynesia', label: 'French Polynesia' },
  { value: 'French Southern Territories (the)', label: 'French Southern Territories (the)' },
  { value: 'Gabon', label: 'Gabon' },
  { value: 'Gambia (the)', label: 'Gambia (the)' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Gibraltar', label: 'Gibraltar' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Greenland', label: 'Greenland' },
  { value: 'Grenada', label: 'Grenada' },
  { value: 'Guadeloupe', label: 'Guadeloupe' },
  { value: 'Guam', label: 'Guam' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Guernsey', label: 'Guernsey' },
  { value: 'Guinea', label: 'Guinea' },
  { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Haiti', label: 'Haiti' },
  { value: 'Heard Island and McDonald Islands', label: 'Heard Island and McDonald Islands' },
  { value: 'Holy See (the)', label: 'Holy See (the)' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Hong Kong', label: 'Hong Kong' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'India', label: 'India' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Iran (Islamic Republic of)', label: 'Iran (Islamic Republic of)' },
  { value: 'Iraq', label: 'Iraq' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Isle of Man', label: 'Isle of Man' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Jersey', label: 'Jersey' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Kazakhstan', label: 'Kazakhstan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Kiribati', label: 'Kiribati' },
  { value: "Korea (the Democratic People's Republic of)", label: "Korea (the Democratic People's Republic of)" },
  { value: 'Korea (the Republic of)', label: 'Korea (the Republic of)' },
  { value: 'Kuwait', label: 'Kuwait' },
  { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
  { value: "Lao People's Democratic Republic (the)", label: "Lao People's Democratic Republic (the)" },
  { value: 'Latvia', label: 'Latvia' },
  { value: 'Lebanon', label: 'Lebanon' },
  { value: 'Lesotho', label: 'Lesotho' },
  { value: 'Liberia', label: 'Liberia' },
  { value: 'Libya', label: 'Libya' },
  { value: 'Liechtenstein', label: 'Liechtenstein' },
  { value: 'Lithuania', label: 'Lithuania' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Macao', label: 'Macao' },
  { value: 'Madagascar', label: 'Madagascar' },
  { value: 'Malawi', label: 'Malawi' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Mali', label: 'Mali' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Marshall Islands (the)', label: 'Marshall Islands (the)' },
  { value: 'Martinique', label: 'Martinique' },
  { value: 'Mauritania', label: 'Mauritania' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Mayotte', label: 'Mayotte' },
  { value: 'Mexico', label: 'Mexico' },
  { value: 'Micronesia (Federated States of)', label: 'Micronesia (Federated States of)' },
  { value: 'Moldova (the Republic of)', label: 'Moldova (the Republic of)' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Montenegro', label: 'Montenegro' },
  { value: 'Montserrat', label: 'Montserrat' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Mozambique', label: 'Mozambique' },
  { value: 'Myanmar', label: 'Myanmar' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'Netherlands (the)', label: 'Netherlands (the)' },
  { value: 'New Caledonia', label: 'New Caledonia' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Niger (the)', label: 'Niger (the)' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'Niue', label: 'Niue' },
  { value: 'Norfolk Island', label: 'Norfolk Island' },
  { value: 'North Macedonia', label: 'North Macedonia' },
  { value: 'Northern Mariana Islands (the)', label: 'Northern Mariana Islands (the)' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Palau', label: 'Palau' },
  { value: 'Palestine, State of', label: 'Palestine, State of' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Papua New Guinea', label: 'Papua New Guinea' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Peru', label: 'Peru' },
  { value: 'Philippines (the)', label: 'Philippines (the)' },
  { value: 'Pitcairn', label: 'Pitcairn' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Puerto Rico', label: 'Puerto Rico' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Romania', label: 'Romania' },
  { value: 'Russian Federation (the)', label: 'Russian Federation (the)' },
  { value: 'Rwanda', label: 'Rwanda' },
  { value: 'Réunion', label: 'Réunion' },
  { value: 'Saint Barthélemy', label: 'Saint Barthélemy' },
  { value: 'Saint Helena, Ascension and Tristan da Cunha', label: 'Saint Helena, Ascension and Tristan da Cunha' },
  { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
  { value: 'Saint Lucia', label: 'Saint Lucia' },
  { value: 'Saint Martin (French part)', label: 'Saint Martin (French part)' },
  { value: 'Saint Pierre and Miquelon', label: 'Saint Pierre and Miquelon' },
  { value: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
  { value: 'Samoa', label: 'Samoa' },
  { value: 'San Marino', label: 'San Marino' },
  { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Senegal', label: 'Senegal' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Seychelles', label: 'Seychelles' },
  { value: 'Sierra Leone', label: 'Sierra Leone' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Sint Maarten (Dutch part)', label: 'Sint Maarten (Dutch part)' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Slovenia', label: 'Slovenia' },
  { value: 'Solomon Islands', label: 'Solomon Islands' },
  { value: 'Somalia', label: 'Somalia' },
  { value: 'South Africa', label: 'South Africa' },
  { value: 'South Georgia and the South Sandwich Islands', label: 'South Georgia and the South Sandwich Islands' },
  { value: 'South Sudan', label: 'South Sudan' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Sudan (the)', label: 'Sudan (the)' },
  { value: 'Suriname', label: 'Suriname' },
  { value: 'Svalbard and Jan Mayen', label: 'Svalbard and Jan Mayen' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Syrian Arab Republic (the)', label: 'Syrian Arab Republic (the)' },
  { value: 'Taiwan (Province of China)', label: 'Taiwan (Province of China)' },
  { value: 'Tajikistan', label: 'Tajikistan' },
  { value: 'Tanzania, the United Republic of', label: 'Tanzania, the United Republic of' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Timor-Leste', label: 'Timor-Leste' },
  { value: 'Togo', label: 'Togo' },
  { value: 'Tokelau', label: 'Tokelau' },
  { value: 'Tonga', label: 'Tonga' },
  { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
  { value: 'Tunisia', label: 'Tunisia' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'Turkmenistan', label: 'Turkmenistan' },
  { value: 'Turks and Caicos Islands (the)', label: 'Turks and Caicos Islands (the)' },
  { value: 'Tuvalu', label: 'Tuvalu' },
  { value: 'Uganda', label: 'Uganda' },
  { value: 'Ukraine', label: 'Ukraine' },
  { value: 'United Arab Emirates (the)', label: 'United Arab Emirates (the)' },
  { value: 'United Kingdom of Great Britain and Northern Ireland (the)', label: 'United Kingdom of Great Britain and Northern Ireland (the)' },
  { value: 'United States Minor Outlying Islands (the)', label: 'United States Minor Outlying Islands (the)' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Uzbekistan', label: 'Uzbekistan' },
  { value: 'Vanuatu', label: 'Vanuatu' },
  { value: 'Venezuela (Bolivarian Republic of)', label: 'Venezuela (Bolivarian Republic of)' },
  { value: 'Viet Nam', label: 'Viet Nam' },
  { value: 'Virgin Islands (British)', label: 'Virgin Islands (British)' },
  { value: 'Virgin Islands (U.S.)', label: 'Virgin Islands (U.S.)' },
  { value: 'Wallis and Futuna', label: 'Wallis and Futuna' },
  { value: 'Western Sahara*', label: 'Western Sahara*' },
  { value: 'Yemen', label: 'Yemen' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Zimbabwe', label: 'Zimbabwe' },
  { value: 'Åland Islands', label: 'Åland Islands' }
];

export const CountriesWithoutCanada = Countries.filter(({label, value}) => label !== 'Canada');

export const Gender = [
  { value: 'Male', label: 'Male' },
  { value: 'Female', label: 'Female' },
  { value: 'Non-Binary', label: 'Non-Binary' },
  { value: 'Transgender - M to F', label: 'Transgender - Male to Female (M to F)' },
  { value: 'Transgender - F to M', label: 'Transgender - Female to Male (F to M)' },
  { value: 'Two-Spirit', label: 'Two-Spirit' },
  { value: 'Another gender not listed', label: 'Another gender not listed above' },
  { value: 'Prefer not to answer', label: 'Prefer not to answer' },
];

export const RegistrationTypes = [
  { label: 'AB Corporate Access Number (ACAN)', value: 'acan' },
  { label: 'Corporate Registation Number', value: 'crn' },
  { label: 'WCB - Alberta Clearance Letter', value: 'wcb-ab' },
  { label: 'WCB - Exempt Industry Letter', value: 'wcb-exempt' },
  { label: 'GST Registration (or Federal Payroll Deduction number)', value: 'gst-fed' },
]

export const CompanyType = [
  { label: 'Corporation', value: 'Corporation' },
  { label: 'Non-Profit Company/Society', value: 'Non-Profit Company/Society' },
  { label: 'Sole Proprietorship', value: 'Sole Proprietorship' },
  { label: 'Partnership', value: 'Partnership' },
]

export const FinancialInstitutions = [
  { label: 'Royal Bank', value: 'Royal Bank' },
  { label: 'The Bank of Montreal', value: 'The Bank of Montreal' },
  { label: 'Canadian Imperial Bank of Commerce', value: 'Canadian Imperial Bank of Commerce' },
  { label: 'The Bank of Nova Scotia', value: 'The Bank of Nova Scotia' },
  { label: 'TD Canada Trust', value: 'TD Canada Trust' },
  { label: 'ATB Financial', value: 'ATB Financial' },
  { label: 'National Bank of Canada', value: 'National Bank of Canada' },
  { label: 'HSBC Bank of Canada', value: 'HSBC Bank of Canada' },
  { label: 'Other', value: 'Other' }
]

export const AccountType = [
  { label: 'Chequing', value: 'Chequing' },
  { label: 'Savings', value: 'Savings' },
  { label: 'Other', value: 'Other' },
]

export const EmployeeTableColumns = [
  { title: 'First Name', field: 'first_name' },
  { title: 'Middle Name', field: 'middle_name' },
  { title: 'Last Name', field: 'last_name' },
  { title: 'Date of Birth', field: 'date_of_birth' },
  { title: 'Start Date', field: 'start_date' },
  { title: 'Position', field: 'position' },
  { title: 'Paid Hours', field: 'paid_hours' },
]

export const SubmissionTypes = [
  { label: 'Organization Information', value: 'organization' },
  { label: 'Employee Submission', value: 'employee' },
  { label: 'Operator Submission', value: 'operator' },
]

export const StatusTypes = [
  { label: 'Approved', value: 'approved' },
  { label: 'Validated', value: 'validated' },
  { label: 'Needs Information', value: 'needs information' },
  { label: 'Denied', value: 'denied' },
  { label: 'Pending', value: 'pending' },
]

export const SubmissionStatusTypes = [
  { label: 'Organization - Validated', value: 'organization_validated' },
  { label: 'Employee - Approved', value: 'employee_approved' },
  { label: 'Operator - Approved', value: 'operator_approved' },
  { label: 'Organization - Pending', value: 'organization_pending' },
  { label: 'Employee - Pending', value: 'employee_pending' },
  { label: 'Operator - Pending', value: 'operator_pending' },
  { label: 'Organization - Denied', value: 'organization_denied' },
  { label: 'Employee - Denied', value: 'employee_denied' },
  { label: 'Operator - Denied', value: 'operator_denied' },
  { label: 'Organization - Needs Information', value: 'organization_needs information' }
]

export const PaymentStatusTypes = [
  { label: 'Operator Benefit - Paid', value: 'operator_paid' },
  { label: 'Operator Benefit - Pending Payment', value: 'operator_pending' },
  { label: 'Operator Benefit - Payment Failed', value: 'operator_failed' },
  { label: 'Operator Benefit - Not Paid', value: 'operator_notPaid' },
  { label: 'Employee Benefit - Paid', value: 'employee_paid' },
  { label: 'Employee Benefit - Pending Payment', value: 'employee_pending' },
  { label: 'Employee Benefit - Payment Failed', value: 'employee_failed' },
  { label: 'Employee Benefit - Not Paid', value: 'employee_notPaid' },

]
export const PaymentDeterminationTypes = [
  { label: 'Employee Benefit - All Paid', value: 'employee_allPaid' },
  { label: 'Employee Benefit - Some Paid', value: 'employee_somePaid' },
  { label: 'Employee Benefit - Not Confirmed Yet', value: 'employee_noConfirm' },

]

export const HealthOptions = [
    {  label: 'Addiction Residential Treatment Centre', value: 'addiction_res_tc'},
    {  label: 'AMH Community/Outpatient Services', value: 'amh_community_outpatient'},
    {  label: 'Opioid Agonist Therapy Clinic', value: 'opioid_agonist_tc'},
    {  label: 'Residential Mental Health Treatment Facility', value: 'residential_menta_health_tf'},
    {  label: 'Supervised Consumption Services or Overdose Prevention Sites' , value: 'supervised_consumption'},
    {  label: 'Long-term care (LTC)' , value: 'ltc'},
    {  label: 'Designated supportive living (DSL)', value: 'dsl'},
    {  label: 'Licensed Supportive Living (LSL)', value: 'lsl'},
    {  label: 'Diagnostic Imaging Clinics', value: 'imaging_clinics'},
    {  label: 'Air Ambulance Operator', value: 'air_ambulance'},
    {  label: 'Licensed Ground ambulance Operator', value: 'ground_ambulance'},
    {  label: 'Home Care', value: 'home_care'},
    {  label: 'Residential Hospice', value: 'hospice'},
    {  label: 'Medical Laboratory under contract with Alberta Precision Laboratories for COVID-19 testing', value: 'med_lab_covid' }
]
export const orderTypes = [
  {label:"Last Updated", value:"lastUpdated"},
  {label:"Organization Name", value:"name"},
  {label:"Submission Date", value:"submissionDate"}
]

export const activeTaskTypes = [
  {label:"Review of Summary Sheet", value: "1" },
  {label:"Finance Review of Grant Agreement", value: "2" },
  {label:"Send Grant Agreement to Operator", value: "3" },
  {label:"Operator Signing of Grant Agreement", value: "4" },
  {label:"AH Signing of Grant Agreement", value: "5" },
  {label: "Send Fully Executed Grant Agreement to Operator", value: "6"}
]

export const paymentBatchTableColumns = [
  { title: 'Batch Name', field: 'batchName' },
  { title: 'Date Created', field: 'dateCreated' },
  { title: 'Created By', field: 'createdBy' },
  { title: 'Total Number of Applications', field: 'totalApplications' },
  { title: 'Total Funding Amount', field: 'fundingAmount' },
  { title: 'Batch Status', field: 'status' },
  { title: '', field: 'view' },
]

 export const EmployeePosition= [
 {label: "Activity/Recreation Worker", value: "Activity/Recreation Worker"},
 {label: "Addictions Worker", value: "Addictions Worker"},
 {label: "Administrative Support", value: "Administrative Support"},
 {label: "Admission Clerk", value: "Admission Clerk"},
 {label: "Advanced Care Paramedic ", value: "Advanced Care Paramedic "},
 {label: "Case Or Care Coordinator", value: "Case Or Care Coordinator"},
 {label: "Chaplain", value: "Chaplain"},
 {label: "Clerk", value: "Clerk"},
 {label: "Client Care Assistant", value: "Client Care Assistant"},
 {label: "Comfort Care Aide", value: "Comfort Care Aide"},
 {label: "Cook", value: "Cook"},
 {label: "Counsellor", value: "Counsellor"},
 {label: "Crisis Intervention Worker", value: "Crisis Intervention Worker"},
 {label: "Dietician", value: "Dietician"},
 {label: "Dining Room Attendant", value: "Dining Room Attendant"},
 {label: "Driver", value: "Driver"},
 {label: "Educator", value: "Educator"},
 {label: "Elder", value: "Elder"},
 {label: "Electroneurophysiology technologists (ENPs)", value: "Electroneurophysiology technologists (ENPs)"},
 {label: "Emergency Medical Responder", value: "Emergency Medical Responder"},
 {label: "Environmental Services ", value: "Environmental Services "},
 {label: "Food Services Worker", value: "Food Services Worker"},
 {label: "Frontline Manager", value: "Frontline Manager"},
 {label: "Graduate Nurse", value: "Graduate Nurse"},
 {label: "Health Care Aide**", value: "Health Care Aide**"},
 {label: "Home Support Worker", value: "Home Support Worker"},
 {label: "Hospitality Services ", value: "Hospitality Services "},
 {label: "Housekeeping", value: "Housekeeping"},
 {label: "Housing Support Aide", value: "Housing Support Aide"},
 {label: "Infection Prevention and Control,Practitioners", value: "Infection Prevention and Control,Practitioners"},
 {label: "Laundry Services", value: "Laundry Services"},
 {label: "Licensed Practical Nurse", value: "Licensed Practical Nurse"},
 {label: "Maintenance Worker", value: "Maintenance Worker"},
 {label: "Medical Laboratory Technologists and ,Technicians*", value: "Medical Laboratory Technologists and ,Technicians*"},
 {label: "Medical Office Assistant", value: "Medical Office Assistant"},
 {label: "Medical Radiation Technologists (MRTs)", value: "Medical Radiation Technologists (MRTs)"},
 {label: "Medical Receptionist", value: "Medical Receptionist"},
 {label: "Medical Sonographers", value: "Medical Sonographers"},
 {label: "Mental Health Worker", value: "Mental Health Worker"},
 {label: "Nursing Care Coordinator", value: "Nursing Care Coordinator"},
 {label: "Nurse Practitioner", value: "Nurse Practitioner"},
 {label: "Occupational Therapist", value: "Occupational Therapist"},
 {label: "Occupational Therapy Assistant", value: "Occupational Therapy Assistant"},
 {label: "Orderly", value: "Orderly"},
 {label: "Other Medical Technologists and Technicians", value: "Other Medical Technologists and Technicians"},
 {label: "Patient Care Aide", value: "Patient Care Aide"},
 {label: "Patient Service Associate", value: "Patient Service Associate"},
 {label: "Personal Care Attendant - Medical", value: "Personal Care Attendant - Medical"},
 {label: "Pharmacist", value: "Pharmacist"},
 {label: "Pharmacy Technician/Assistant", value: "Pharmacy Technician/Assistant"},
 {label: "Physiotherapist", value: "Physiotherapist"},
 {label: "Physiotherapy Assistant", value: "Physiotherapy Assistant"},
 {label: "Primary Care Paramedic", value: "Primary Care Paramedic"},
 {label: "Psychiatric Aide", value: "Psychiatric Aide"},
 {label: "Psychologist", value: "Psychologist"},
 {label: "Receptionist", value: "Receptionist"},
 {label: "Recreation Assistant", value: "Recreation Assistant"},
 {label: "Recreational Therapist", value: "Recreational Therapist"},
 {label: "Registered Dietician", value: "Registered Dietician"},
 {label: "Registered Nurse", value: "Registered Nurse"},
 {label: "Registered Psychiatric Nurse", value: "Registered Psychiatric Nurse"},
 {label: "Registered Social Worker", value: "Registered Social Worker"},
 {label: "Rehabilitation Worker", value: "Rehabilitation Worker"},
 {label: "Resident Care Aide - Medical", value: "Resident Care Aide - Medical"},
 {label: "Respiratory Therapist", value: "Respiratory Therapist"},
 {label: "Security Staff and Screeners", value: "Security Staff and Screeners"},
 {label: "Social Worker (Medical, Psychiatric)", value: "Social Worker (Medical, Psychiatric)"},
 {label: "Speech Language Pathologist", value: "Speech Language Pathologist"},
 {label: "Speech Therapy Assistant", value: "Speech Therapy Assistant"},
 {label: "Spiritual Care Worker", value: "Spiritual Care Worker"},
 {label: "Staffing Coordinator", value: "Staffing Coordinator"},
 {label: "Support Service Worker", value: "Support Service Worker"},
 {label: "Therapist", value: "Therapist"},
 {label: "Therapy Assistant", value: "Therapy Assistant"},
 {label: "Undergraduate Nurse", value: "Undergraduate Nurse"},
 {label: "Unit Clerk", value: "Unit Clerk"},
 {label: "Visitation Coordinator", value: "Visitation Coordinator"},
 {label: "Volunteer Coordinator", value: "Volunteer Coordinator"}
 ]

 export const PaymentStatusOptions = [
  {label:"Not Paid", value: "Not Paid", LabelComponent: FiberManualRecordIcon, style: {color: 'grey'} },
  {label:"Payment Failed", value: "Payment Failed", LabelComponent: FiberManualRecordIcon, style: {color: 'red'} },
  {label:"Pending Payment", value: "Pending Payment", LabelComponent: FiberManualRecordIcon,style: {color: '#ffb835'} },
  {label:"Paid", value: "Paid", LabelComponent: FiberManualRecordIcon, style: {color: '#16c92e'} },
]

export const ReportOptions = [
  {label: "Approved Application Totals", value: "DETAILED_REPORT_1"},
  {label: "Approved Summary Sheet Totals", value: "DETAILED_REPORT_2"},
  {label: "Total Amounts Paid", value: "DETAILED_REPORT_3"},
  {label: "Weekly Report", value: "SIMEN_WEEKLY_REPORT"},
  {label: "Assessed Applications CWB", value: "ASSESSED_APPLICATIONS"},
]