apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: 'true'
objects:
  - apiVersion: v1
    stringData:
      BCAAP_SMALL_FORM: ${BCAAP_SMALL_FORM}
      BCAAP_FACILITY_FORM: ${BCAAP_FACILITY_FORM}
      BCAAP_ENVIRONMENT_FORM: ${BCAAP_ENVIRONMENT_FORM}
      BCAAP_LARGE_FORM: ${BCAAP_LARGE_FORM}
      BCAAP_SMALL_KEY: ${BCAAP_SMALL_KEY}
      BCAAP_FACILITY_KEY: ${BCAAP_FACILITY_KEY}
      BCAAP_ENVIRONMENT_KEY: ${BCAAP_ENVIRONMENT_KEY}
      BCAAP_LARGE_KEY: ${BCAAP_LARGE_KEY}
    kind: Secret
    metadata:
      name: ${APP_NAME}-chefs-env
    type: Opaque
parameters:
  - description: Form id for small project
    displayName: BCAAP_SMALL_FORM
    name: BCAAP_SMALL_FORM
    required: true
    value: ''
  - description: Form id for large project
    displayName: BCAAP_LARGE_FORM
    name: BCAAP_LARGE_FORM
    required: true
    value: ''
  - description: Form id for facility project
    displayName: BCAAP_FACILITY_FORM
    name: BCAAP_FACILITY_FORM
    required: true
    value: ''
  - description: Form id for environment project
    displayName: BCAAP_ENVIRONMENT_FORM
    name: BCAAP_ENVIRONMENT_FORM
    required: true
    value: ''
  - description: API key for small project
    displayName: BCAAP_SMALL_KEY
    name: BCAAP_SMALL_KEY
    required: true
    value: ''
  - description: API key for large project
    displayName: BCAAP_LARGE_KEY
    name: BCAAP_LARGE_KEY
    required: true
    value: ''
  - description: API key for facility project
    displayName: BCAAP_FACILITY_KEY
    name: BCAAP_FACILITY_KEY
    required: true
    value: ''
  - description: API key for environment project
    displayName: BCAAP_ENVIRONMENT_KEY
    name: BCAAP_ENVIRONMENT_KEY
    required: true
    value: ''
  - description: Application name
    displayName: APP_NAME
    name: APP_NAME
    required: true
    value: 'pbgp'
