apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: 'true'
objects:
  - apiVersion: v1
    stringData:
      CHEFS_API_KEYS: ${CHEFS_API_KEYS}
      CHEFS_FORM_IDS: ${CHEFS_FORM_IDS}
    kind: Secret
    metadata:
      name: ${APP_NAME}-chefs-env
    type: Opaque
parameters:
  - description: An array of API Keys
    displayName: CHEFS_API_KEYS
    name: CHEFS_API_KEYS
    required: true
    value: ''
  - description: An array of form ids
    displayName: CHEFS_FORM_IDS
    name: CHEFS_FORM_IDS
    required: true
    value: ''
  - description: Application name
    displayName: APP_NAME
    name: APP_NAME
    required: true
    value: 'pbgp'
