kind: Template
apiVersion: template.openshift.io/v1
labels:
  app: ${APP_NAME}
parameters:
  - name: APP_NAME
    description: App name that OpenShift objects will be prefixed with
    required: true
  - name: IMAGE_NAMESPACE
    description: Namespace from which to pull the image
    required: true
  - name: IMAGE_TAG
    description: Image tag from image stream
    value: latest
    required: true
  - name: SERVER_PORT
    description: Port the server will be exposed on
    value: "8080"
    required: true
  - name: CONFIG_VERSION
    description: The github repository version of Config (Commit SHA)
    value: default
  - name: REPLICAS
    description: The number of replicas of deployments
    value: "2"

objects:
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APP_NAME}-server
      annotations:
        haproxy.router.openshift.io/timeout: 90s
        haproxy.router.openshift.io/disable_cookies: true
    spec:
      host: ""
      port:
        targetPort: web
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-server
        weight: 100
      wildcardPolicy: None
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-server
    spec:
      strategy:
        type: Rolling
        activeDeadlineSeconds: 21600
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}-server
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}-server:${IMAGE_TAG}
              namespace: ${IMAGE_NAMESPACE}
          type: ImageChange
        - type: ConfigChange
      replicas: "${{REPLICAS}}"
      selector:
        name: ${APP_NAME}-server
      template:
        metadata:
          name: ${APP_NAME}-server
          labels:
            name: ${APP_NAME}-server
        spec:
          containers:
            - name: ${APP_NAME}-server
              env:
                - name: APP_ENV
                  value: ${IMAGE_TAG}
                - name: POSTGRES_HOST
                  value: ${APP_NAME}-patroni
                - name: POSTGRES_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: db-name
                      name: ${APP_NAME}-patroni
                - name: POSTGRES_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: db-username
                      name: ${APP_NAME}-patroni
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: db-password
                      name: ${APP_NAME}-patroni
                - name: PORTGRES_PORT
                  value: "5432"
                - name: APP_PORT
                  value: "8080"
                - name: CONFIG_VERSION
                  value: ${CONFIG_VERSION}
              image: image-registry.openshift-image-registry.svc:5000/${IMAGE_NAMESPACE}/${APP_NAME}-server:${IMAGE_TAG}
              ports:
                - containerPort: "${{SERVER_PORT}}"
                  protocol: TCP
              readinessProbe:
                failureThreshold: 5
                httpGet:
                  path: /api/v1/version
                  port: ${{SERVER_PORT}}
                initialDelaySeconds: 15
                periodSeconds: 15
              livenessProbe:
                failureThreshold: 5
                httpGet:
                  path: /api/v1/version
                  port: ${{SERVER_PORT}}
                initialDelaySeconds: 15
                periodSeconds: 15
              resources:
                limits:
                  cpu: 500m
                  memory: 2Gi
                requests:
                  cpu: 250m
                  memory: 1Gi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          dnsPolicy: ClusterFirst
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-server
    spec:
      ports:
        - name: web
          protocol: TCP
          port: ${{SERVER_PORT}}
          targetPort: ${{SERVER_PORT}}
      selector:
        name: ${APP_NAME}-server
      type: ClusterIP
      sessionAffinity: None
