export enum FormSteps {
  CONTACT_INFO = 'CONTACT_INFO',
  GENERAL_INFO = 'GENERAL_INFO',
  FACILITY_INFO = 'FACILITY_INFO',
  FUNDING_ELIGIBILITY = 'FUNDING_ELIGIBILITY',
  ENVIRONMENTAL_CONSIDERATION = 'ENVIRONMENTAL_CONSIDERATION',
  FUNDING_INFO = 'FUNDING_INFO',
  SUPPORT_DOCUMENTATION = 'SUPPORT_DOCUMENTATION',
  AUTHORIZATION = 'AUTHORIZATION',
}
