export enum FormSteps {
  CONTACT_INFO = 'CONTACT_INFO',
  GENERAL_INFO = 'GENERAL_INFO',
  FACILITY_INFO = 'FACILITY_INFO',
  FUNDING_ELIGIBILITY = 'FUNDING_ELIGIBILITY',
  ENVIRONMENTAL_CONSIDERATION = 'ENVIRONMENTAL_CONSIDERATION',
  FUNDING_INFO = 'FUNDING_INFO',
  SUPPORT_DOCUMENTATION = 'SUPPORT_DOCUMENTATION',
  AUTHORIZATION = 'AUTHORIZATION',
}

export enum ApplicationStatus {
  INITIAL_REVIEW = 'INITIAL_REVIEW',
  DISCARD = 'DISCARD',
  FUNDING_REVIEW = 'FUNDING_REVIEW',
  BROADER_REVIEW = 'BROADER_REVIEW',
  WORKSHOP = 'WORKSHOP',
}

export enum ApplicationType {
  LARGE_PROJECT = 'LP',
  SMALL_PROJECT = 'SP',
  ENVIRONMENT_PLANNING = 'EP',
  DEVELOPMENT_PLANNING = 'DP',
}
