
const header = 'By submitting this Application Form ("Application"), I confirm that:'


const text = ['I am authorized by the organization to execute the within Application.',
  'I confirm the organization has provided true, complete and correct information in this Application.',
  'I confirm the organization understands that if any false or misleading information is submitted or any relevant or significant fact is concealed, or any other misrepresentation occurs, the Minister may decline the organization\'s application or terminate the Grant Agreement(s), and may require the organization to repay any grant funds received.The Minster may also ban the organization from applying for further grants for an unspecified period of time.',
  'I confirm the organization understands that the information contained in this form, including personal information may be disclosed to an authorized employee, agent or contractor of the Government of Alberta for the purposes of determining eligibility for the Alberta\'s Critical Worker Benefit Program, and Alberta Health\'s Operator COVID-19 Support Funding; to assist in administering the Alberta Critical Worker Benefit Program, and Alberta Health\'s Operator COVID - 19 Support Funding, and to monitor and assess and evaluate Alberta\'s Critical Worker Benefit and Alberta Health\'s Operator COVID - 19 Support Funding, including auditing organization compliance and the terms and conditions of this program after the applications have been concluded.',
  'I confirm the organization has read the version of Alberta\'s Critical Worker Benefit Program Guidelines and Alberta Health\'s Operator COVID-19 Support Funding Guidelines applicable at the time of the Application and acknowledges the organization will be bound by them.  The organization agrees to regularly review the Alberta Critical Worker Benefit program website and Alberta\'s Critical Worker Benefit Program Guidelines for program updates.I confirm the organization understands that the Alberta\'s Critical Worker Benefit Program Guidelines and Alberta Health\'s Operator COVID - 19 Support Funding Guidelines forms part of the Grant Agreement.',
  'I confirm the organization understands that any employee or former employee declared by the organization as eligible for the Alberta\'s Critical Worker Benefit Program, and subsequently approved by the Government of Alberta, will receive the lump sum benefit approved and paid to in the order of the organization and I confirm that the organization will attest and / or provide proof that these payments were delivered to eligible and approved employees, within four weeks of the date on which payment was received by the organization from the Government of Alberta.',
  'I confirm the organization will inform and seek consent from each employee identified as eligible for Alberta\'s Critical Worker Benefit Program regarding the collection of personal information of the employee, including but not limited to, the employee\'s payroll information and documentation of employment which will be provided to Government of Alberta for the purposes of eligibility for grant funding.',
  'I confirm the organization understands that, following the completion of the grant(s), the organization will complete all required reporting as specified in the Alberta Critical Benefit Program Guidelines and the Operator COVID-19 Support Funding Guidelines.']
const confirm = ['I confirm the organization understands this application is not approved until it has been signed by the Minister.',
  'I confirm the organization understands that meeting the eligibility criteria does not guarantee grant funding, and that the Minister retains the sole discretion to']

const agree = ['approve an application',
  'enter into the Grant Agreement',
  'approve each employee, and',
  'allocate grant funds.']


const last = ['I confirm the organization understand the Application will be considered on a "first come, first approved" basis, and an incomplete Application will not be considered and approved.',
  'I confirm the organization understand and assume any and all risk and responsibility, including financial risks if any, to ensure approved employees receive the funds for with employees were approved.',
  'I confirm the organization understands that 7.66% of the approved total grant may be used at the discretion of the organization to cover, fully or partially, the administration costs absorbed by distributing approved grant funding to the approved employees.  This 7.66% is distinct and provided to the organization over and above the funding approved per employee; it does not comprise any portion of the $1,200 lump sum allocated for approved employees.',
  'Missing Copy',
  'I confirm the organization understands no grant funds will be allocated until the Minister approves the eligible beds and hours under the Operator COVID-19 Support Funding and employee(s) identified by the organization with the Critical Worker Benefit application, and the organization submits all required information with the application to confirm organization and employee eligibility.',
  'I confirm the organization understands that this application and the these declarations form part of the Alberta\'s Critical Work Benefit Program Grant Agreement and the Operator COVID - 19 Support Funding Grant Agreement between the organization and the Minister, and I confirm the organization agrees to be bound by the terms and condition therein.']
